employeePortal/urls.py
from django.contrib import admin
from django.urls import path,include
from myApp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('myApp/',include('myApp.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myApp/urls.py
from django.urls import path
from myApp import views

app_name = 'myApp'

urlpatterns = [
    path('login/',views.uslogin,name='login'),
    path('home/',views.home,name='home'),
    path('index/',views.index,name='index'),
    path('leave/',views.leaveView,name='leave'),
    path('contact/',views.contact,name='contact'),
    path('health/',views.health,name='health'),
    path('holiday/',views.holidays,name='holidays'),
    path('job/',views.job,name='job'),
    path('salary/',views.salary,name='salary'), 
    path('submission/',views.submission,name='submission'), 
    path('directory/',views.directory,name='directory'), 
    path('family/',views.family,name='family'), 
    path('check_user',views.check_user,name='check_user'), 
    path('uslogout/',views.uslogout,name='logout'),
    path('personal_info/',views.personal_info,name='personal_info'),
    path('health_record/',views.health_info,name='health_record'),
    path('family_record/',views.family_info,name='family_record'),
    path('change_password',views.change_password,name='change_password'),
    path('input_salary',views.input_salary,name='inputsalary'),
    path('input_job',views.input_job,name='input_job'),
    path('change_profile',views.change_profile,name='change_profile'),
    path('user_profile',views.profile,name='user_profile'),
    path('hrdash',views.hr_dash,name='hrdash'),
    path('SignUpApprove',views.SignUp_Approve,name='SignUpApprove'),   
    path('documentReview',views.document_review,name='documentReview'),    
    path('leave_approval',views.leave_approval,name='leaveapproval'),    
    path('send_mail',views.send_mail,name='mail'),    
    path('documentAppprove',views.document_approval,name='documentApprove'),    
    path('hr_password',views.hr_password,name='hrpassword'),    
    path('announce',views.announcements,name='announce'),    
    path('leaveDetails',views.leaveDetails,name='leavedet'),    
    path('docDetails',views.doc_Details,name='docDetails'),    
    path('leave_assign',views.leave_assign,name='leaveassign'),     
    path('forgot_password',views.forgot_password,name='forgotpassword'),    
    path('holidayupdate',views.holiday_update,name='holidayupdate'),   
    path('addattendance',views.addattendance,name='addatt'),    
    path('hrsend_mail',views.hrsend_mail,name='hr_mail'),    
    path('event',views.events,name='event'),    
    path('changestatus',views.changestatus,name="changestatus"),
    path('hrchangestatus',views.hr_changestatus,name="hrchangestatus"),
    path('attendanceUser',views.attendanceUser,name="attendanceUser"),
    path('HRprofile',views.HRprofile,name="HR_profile"),
    path('HRchange_profile',views.HRchange_profile,name="hrchangeprofile"),
    path('calendr',views.calendr,name="calendr"),
    path('showattendance',views.show_attendance,name="showattendance"),
    path('getattendance',views.getattendance,name="getattendance"),
    path('getstatus',views.get_status,name="getstatus"),    
    path('hrdir',views.hrdirectory,name="hrdir"),    
   
  
]

myApp/models.py
from django.db import models
from django.contrib.auth.models import User
class employee(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    country = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    contact = models.IntegerField(blank=True,null=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d',blank=True,null=True)

    def __str__(self):
        return self.user.username

class HR(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    sub = (('Mr.','Mr.'),('Mrs.','Mrs.'),('Miss','Miss'))
    gender = models.CharField(choices=sub,max_length=10,blank=True,null=True)
    country = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    contact = models.IntegerField(blank=True,null=True)
    image = models.ImageField(upload_to='images/%Y/%m/%d',blank=True,null=True)

    def __str__(self):
        return self.user.username
 

class emp_details(models.Model):
    emp_name = models.ForeignKey(employee,on_delete=models.CASCADE)
    name = models.CharField(max_length=200,blank= True,null=True)
    sub = (('Mr.','Mr.'),('Mrs.','Mrs.'),('Miss','Miss'))
    title = models.CharField(choices=sub,max_length=10,blank=True,null=True)
    date_of_birth = models.DateField(blank= True,null=True)
    email = models.EmailField(max_length=200,blank= True)
    p_phone = models.IntegerField(blank= True,null=True)
    a_phone = models.IntegerField(blank= True,null=True)
    address = models.CharField(max_length=200,blank= True,null=True)
    city = models.CharField(max_length=100,blank= True,null=True)
    state = models.CharField(max_length=200,blank= True,null=True)
    country = models.CharField(max_length=200,blank= True,null=True)
    pin_code = models.IntegerField(blank= True,null=True)
    height = models.DecimalField(max_digits=10,decimal_places=2,blank= True,null=True)
    sub_group = (('A-','A-'),('A+','A+'),('B+','B+'),('B-','B-'),('O+','O+'),('O-','O-'),('AB+','AB+'),('AB-','AB-'))
    blood_group = models.CharField(choices=sub_group,max_length=10,blank= True,null=True)
    weight = models.DecimalField(max_digits=10,decimal_places=2,blank= True,null=True)
    disease = models.CharField(max_length=200,blank= True,null=True)
    sub_eye = (('Brown','Brown'),('Black','Black'))
    left_eye = models.CharField(choices=sub_eye,max_length=20,blank= True,null=True)
    right_eye = models.CharField(choices=sub_eye,max_length=20,blank= True,null=True)
    left_ear = models.CharField(max_length=200,blank= True,null=True)
    right_ear = models.CharField(max_length=200,blank= True,null=True)
    left_hand = models.CharField(max_length=200,blank= True,null=True)
    right_hand = models.CharField(max_length=200,blank= True,null=True)
    marriage = (('Single','Single'),('Married','Married'))
    marital_status = models.CharField(choices=marriage,max_length=10,blank= True,null=True)
    sub = (('yes','yes'),('no','no'))
    spouse_working = models.CharField(choices=sub,max_length=5, blank= True,null=True)
    children = models.IntegerField(blank= True,null=True)
    child_study = models.CharField(choices=sub,max_length=2, blank= True,null=True)
    father = models.CharField(max_length=200,blank= True,null=True)
    mother = models.CharField(max_length=200,blank= True,null=True)
    sibling = models.IntegerField(blank= True,null=True)
    income = models.DecimalField(max_digits=10,decimal_places=2,blank= True,null=True)
    basic_salary = models.DecimalField(max_digits=10,decimal_places=2,blank= True,null=True)
    deduction = models.DecimalField(max_digits=10,decimal_places=2, blank= True,null=True)
    bonus = models.DecimalField(max_digits=10,decimal_places=2, blank= True,null=True)
    total_income = models.DecimalField(max_digits=10,decimal_places=2, blank= True,null=True)
    bank = models.CharField(max_length=100,blank= True,null=True)
    bank_account = models.CharField(max_length=50, blank= True,null=True)
    monthly_pay = models.DecimalField(max_digits=10,decimal_places=2,blank= True,null=True)
    val = (('bank','bank'),('cash','cash'))
    payment_method = models.CharField(choices=val,max_length=200,blank= True,null=True)
    date_of_probation = models.DateField(blank=True,null=True)
    sub_pos=(('Software Developer','Software Developer'),('Software Tester','Software Tester'))
    position = models.CharField(choices=sub_pos,max_length=200,blank= True,null=True)
    sub_dept = (('Hr Department','Hr Department'),('Networking','Networking'),('IT','IT'))
    dept = models.CharField(choices=sub_dept,max_length=100,blank= True,null=True)
    sub_level = (('Junior','Junior'),('Senior','Senior'))
    level = models.CharField(choices=sub_level,max_length=100,blank= True,null=True)
    sub_emp = (('Permanent','Permanent'),('Temporary','Temporary'))
    employee_type = models.CharField(choices=sub_emp,max_length=100,blank= True,null=True)
    holidays = models.CharField(max_length=200,blank= True,null=True)
    workdays = models.CharField(max_length=200,blank= True,null=True)
    date_of_joining = models.DateTimeField(auto_now_add = True,null=True)

    def __str__(self):
        return  self.emp_name.user.username

class leave(models.Model):
    leave = models.ForeignKey(employee,on_delete=models.CASCADE)
    sub = (('CL','CL'),('PL','PL'),('C-off','C-off'),('RH','RH'))
    leave_type = models.CharField(choices=sub,max_length=10,blank=True,null=True)
    CL_balance = models.IntegerField(blank=True,null=True)
    PL_balance = models.IntegerField(blank=True,null=True)
    Coff_balance = models.IntegerField(blank=True,null=True)
    RH_balance = models.IntegerField(blank=True,null=True)
    PL_taken = models.IntegerField(blank=True,null=True)
    CL_taken = models.IntegerField(blank=True,null=True)
    Coff_taken = models.IntegerField(blank=True,null=True)
    RH_taken = models.IntegerField(blank=True,null=True)
    CL_applied = models.IntegerField(blank=True,null=True)
    PL_applied = models.IntegerField(blank=True,null=True)
    Coff_applied = models.IntegerField(blank=True,null=True)
    RH_applied = models.IntegerField(blank=True,null=True)
    CL_rejected = models.IntegerField(blank=True,null=True)
    PL_rejected = models.IntegerField(blank=True,null=True)
    Coff_rejected = models.IntegerField(blank=True,null=True)
    RH_rejected = models.IntegerField(blank=True,null=True)
    valid_until = models.DateField(blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    from_date = models.DateField(blank=True,null=True)
    to_date = models.DateField(blank=True,null=True)
    for_days = models.IntegerField(blank=True,null=True)
    session = models.CharField(max_length=100,blank=True,null=True)
    reason = models.CharField(max_length=100,blank=True,null=True)
    val = (('Approve','Approve'),('Pending','Pending'),('Rejected','Rejected'))
    sub_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    status = models.CharField(choices=val, max_length=10,blank=True,null=True,default="Pending")

    def __str__(self):
        return self.leave.user.username

class leaveAssign(models.Model):
    ltype= models.CharField(max_length=200)
    total = models.IntegerField(null=True)
    date = models.DateField(null=True)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.ltype
import datetime
class leaveApply(models.Model):
    leave_type = models.ForeignKey(leaveAssign,on_delete=models.CASCADE)
    emp_id = models.ForeignKey(employee,on_delete=models.CASCADE)
    from_date = models.DateField(blank=True,null=True)
    to_date = models.DateField(blank=True,null=True)
    for_days = models.IntegerField(blank=True,null=True)
    val = (('Approve','Approve'),('Pending','Pending'),('Rejected','Rejected'))
    status = models.CharField(choices=val, max_length=10,blank=True,null=True,default="Pending")
    session = models.CharField(max_length=100,blank=True,null=True)
    description = models.CharField(max_length=200,blank=True,null=True)    
    sub_date = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    def __str__(self):
        return self.leave_type.ltype

class document(models.Model):
    doc = models.ForeignKey(employee,on_delete=models.CASCADE)
    sub = (('HR Policy','HR Policy'),('Finance Policy','Finance Policy'))
    workflow = models.CharField(choices=sub, max_length=50,blank=True,null=True)
    document = models.FileField(upload_to='documents/%Y/%m/%d',blank=True,null=True)
    reference = models.CharField(max_length=200,blank=True,null=True)
    description = models.CharField(max_length=300,blank=True,null=True)
    submission_date = models.DateTimeField(auto_now_add=True,null=True)
    sub_status = (('Approve','Approve'),('Pending','Pending'),('Rejected','Rejected'))
    status = models.CharField(choices=sub_status,max_length=10,blank=True,null=True,default="Pending")


class designation(models.Model):
    d_name = models.CharField(max_length=50)
    d_salary = models.DecimalField(max_digits=10,decimal_places=2,blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True,null=True)

class Notification(models.Model):
    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    status = models.BooleanField(default=False,null=True,blank=True)
    content=models.CharField(max_length=500,null=True,blank=True)
    notify_on = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    def __str__(self):
        return self.user_id.username  

class HrNotification(models.Model):
    notify_type = models.CharField(max_length=100,null=True,blank=True)
    status = models.BooleanField(default=False,null=True,blank=True)
    content=models.CharField(max_length=500,null=True,blank=True)
    notify_on = models.DateTimeField(auto_now_add=True,null=True,blank=True)

    def __str__(self):

templates/SignupApproval.html
{% extends 'hr.html'%}
{% load staticfiles %}
{% block head %}
{% endblock %}
{% block mycode %}
<div class="container">
  <div class="row">
    <div class="col-md-8" style="margin-left:10%;margin-right:20%;">
      <table class="table table-striped">
        <thead style="background:#D2691E">
          <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Action</th>
            
          </tr>
        </thead>
        <tbody style="background:cornsilk">
          {% for i in all %}
          <tr>
              <td>{{i.user.first_name}} {{i.user.last_name}}</td>
              <td>{{i.user.id}} {{i.user.username}}</td>
              <td>
                {% if i.user.is_active %}
                <a href="{% url 'myApp:SignUpApprove' %}?id={{i.user.id}}&action=app" class="btn btn-warning">Deactivate</a>
                {% else %}
                <a href="{% url 'myApp:SignUpApprove' %}?id={{i.user.id}}&action=app" class="btn btn-success">Approve</a>
                {% endif %}
                <a href="{% url 'myApp:SignUpApprove' %}?id={{i.id}}&action=delete" class="btn btn-danger">Delete</a>
                
              </td>
          </tr>
          {% endfor %}
         </tbody>
      </table>
    </div>
  </div>

</div>
          
                   
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>         
      <script src="{% static 'animate/js/animate.js' %}"></script> 

{% endblock %}

templates/hr.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>Dashboard</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css" />    
    <!-- FontAwesome 4.3.0 -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />    
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins 
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'plugins/iCheck/flat/blue.css' %}" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="{% static 'plugins/morris/morris.css' %}" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="{% static 'plugins/datepicker/datepicker3.css' %}" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="{% static 'plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="{% static 'images/employee.png' %}">

    <style>
    .bg{
      background:rgba(0,0,0,0.5);
    }
    .text{
      color:white;
    }
    #calendar{
      color:white !important;
    }
    @media screen and (max-width:770px){
        .space{
          margin-top:0px !important;
          text-align:left !important;
        }
      }
    </style>
  </head>
  <body class="skin-blue">
    <div class="wrapper">
      
      <header class="main-header">
        <!-- Logo -->
       <p class="logo space" style="background:#D2691E;position:fixed"><b>HR&nbsp</b>Portal</p>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-fixed-top" style="background: #D2691E" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button" style="background:#D2691E">
            <span class="sr-only" >Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!--  -->
                
            
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image"/>
                  <span class="hidden-xs">{{user.first_name}} {{user.last_name}}</span>
                </a>
                <ul class="dropdown-menu" >
                  <!-- User image -->
                  <li class="user-header" style="background: rgb(230, 126, 51)" >
                    <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image" />
                    <p>
                      {{user.first_name}} {{user.last_name}}
                      <small>Member Since {{user.date_joined}}</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <!-- Menu Footer-->
                  <li class="user-footer" style="background: rgb(230, 121, 43)" >
                    <div class="pull-left">
                      <a href="{% url 'myApp:logout'%}" class="btn btn-success">Sign Out</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'myApp:hrpassword' %}" class="btn btn-success ">Change Password</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar" style="position:fixed">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
              <p>{{user.first_name}} {{user.last_name}}</p>
            </div>
          </div>
          <!-- search form -->
         
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu" >
            <li class="active treeview">
              <a href="{% url 'myApp:hrdash' %}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span> 
              </a>
            </li>
            <li class="treeview">
              <a href="{% url 'myApp:SignUpApprove' %}" onclick="myfun('signup')">
                <i class="fa fa-dashboard"></i> <span>SignUp approval</span> <sup><span class="badge alert-danger">{{notifications.signup}}</span></sup>
              </a>
            </li>
            <li class="treeview">
              <a href="#" onclick="myfun('leave')">
                <i class="fa fa-laptop"></i>
                <span>Leave</span><sup><span class="badge alert-danger">{{notifications.leaves}}</span></sup>
                <!-- {% for i in notify %}
                {{i.content}}
                {% endfor %} -->
                <i class="fa fa-angle-left pull-right">

                </i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'myApp:leaveassign' %}"><i class="fa fa-circle-o"></i>Leave Assign</a></li>
                <li><a href="{% url 'myApp:leaveapproval' %}"><i class="fa fa-circle-o"></i>Leave Approval</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="{% url 'myApp:documentApprove' %}" onclick="myfun('document')">
                <i class="fa fa-laptop"></i>
                <span>Documents</span><sup><span class="badge alert-danger" id="badg">{{notifications.docs}}</span></sup>
              </a>
            </li>
            <li class="treeview">
              <a href="{% url 'myApp:holidayupdate' %}">
                <i class="fa fa-table"></i> <span>Holidays Updates</span>
              </a>
            </li>
            <li class="treeview">
              <a href="{% url 'myApp:hrdir' %}">
                <i class="fa fa-edit"></i> <span>Employee Directory</span>
              </a>
            </li>
            <!-- <li class="treeview">
              <a href="{% url 'myApp:announce' %}">
                <i class="fa fa-edit"></i> <span>Announcements</span>
              </a>
            </li> -->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i>
                <span>Announcements</span>
                <i class="fa fa-angle-left pull-right">

                </i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'myApp:announce' %}"><i class="fa fa-circle-o"></i>Notice Update</a></li>
                <li><a href="{% url 'myApp:event' %}"><i class="fa fa-circle-o"></i>Upcoming Events</a></li>
              </ul>
            </li>
            <li class="treeview">
                <a href="#">
                  <i class="fas fa-address-card"></i> <span>Profile</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
      
                  <li><a href="{% url 'myApp:HR_profile' %}"><i class="fa fa-circle-o"></i>HR profile</a></li>
                  <li><a href="{% url 'myApp:hrchangeprofile' %}"><i class="fa fa-circle-o"></i>Change Profile</a></li>
                </ul>
              </li>
            <li>
              <a href="{% url 'myApp:calendr' %}">
                <i class="fa fa-calendar"></i> <span>Calendar</span>
              </a>
            </li>
            <li>
              <a href="{% url 'myApp:hr_mail' %}">
                <i class="fa fa-envelope"></i> <span>Send Mail</span>
                <!-- <small class="label pull-right bg-yellow">12</small> -->
              </a>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>
      <script>
        function myfun(t){
          $.ajax({
            url:"{% url 'myApp:hrchangestatus'%}",
            type:'get',
            data:{tp:t},
            success:function(data){
             
            }
          })
        }
        </script>
      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper" id='all-content' style="background-image:url('images/body-bg.jpg');background-size:cover;">
        <!-- Content Header (Page header) -->
        <section class="content-header space" style="margin-top:35px;background:rgb(169, 214, 169);">
          <h1 class="text" style="color:black;">
            Secours.we
          </h1>
        </section>
        <div style="background-image: url('{%static "images/pexels-photo-1181304.jpeg"%}'); height:100vh; background-size: 100% 100%; width:100%">
        {% block mycode %}
        {% endblock %}
      </div>
        <!-- Main content -->
        
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.0
        </div>
        <strong>Copyright &copy; 2019 <a href="http://almsaeedstudio.com">ACET Studio</a>.</strong> All rights reserved.
      </footer>
    </div><!-- ./wrapper -->

    <script>
    
    </script>
   <!-- jQuery 2.1.3 -->
   <script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js' %}"></script>
   <!-- jQuery UI 1.11.2 -->
   <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
   <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
   <script>
     $.widget.bridge('uibutton', $.ui.button);
   </script>
   <!-- Bootstrap 3.3.2 JS -->
   <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>    
   <!-- Morris.js charts -->
   <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
   <script src="{% static 'plugins/morris/morris.min.js' %}" type="text/javascript"></script>
   <!-- Sparkline -->
   <script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>
   <!-- jvectormap -->
   <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}" type="text/javascript"></script>
   <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}" type="text/javascript"></script>
   <!-- jQuery Knob Chart -->
   <script src="{% static 'plugins/knob/jquery.knob.js' %}" type="text/javascript"></script>
   <!-- daterangepicker -->
   <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}" type="text/javascript"></script>
   <!-- datepicker -->
   <script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}" type="text/javascript"></script>
   <!-- Bootstrap WYSIHTML5 -->
   <script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}" type="text/javascript"></script>
   <!-- iCheck -->
   <script src="{% static 'plugins/iCheck/icheck.min.js' %}" type="text/javascript"></script>
   <!-- Slimscroll -->
   <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
   <!-- FastClick -->
   <script src="{% static 'plugins/fastclick/fastclick.min.js' %}"></script>
   <!-- AdminLTE App -->
   <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>

   <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
   <script src="{% static 'dist/js/pages/dashboard.js' %}" type="text/javascript"></script>

   <!-- AdminLTE for demo purposes -->
   <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
  </body>
</html>

templates/input_salary.html
<!DOCTYPE html>
{% extends "hr.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
{% block mycode %}
<div class="container">
        <div class="row">

            <div class="col-md-6 mx-auto"style="margin-left:20%;margin-left:20%; background:cornsilk;border:2px solid #D2691E;">
                <h2>Salary Details</h2>
                <div style="background:#D2691E;height:2px;width:35%;"></div>
                <div class="p-5">
                    <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                        {% bootstrap_form form%}
                            <input type="submit">
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}